package com.caseflow.ticket.api.mapper;

import com.caseflow.ticket.api.dto.CreateTicketRequest;
import com.caseflow.ticket.api.dto.UpdateTicketRequest;
import com.caseflow.ticket.domain.Ticket;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.mapstruct.ReportingPolicy;

@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        unmappedSourcePolicy = ReportingPolicy.IGNORE
)
public interface TicketMapper {

    /**
     * Maps creatable fields from request. ticketNo is generated by service.
     * status, assignedUserId, assignedGroupId, and closedAt are service-managed.
     * createdBy is a service-layer concern (used for history), not an entity field.
     */
    @Mapping(target = "ticketNo", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "assignedUserId", ignore = true)
    @Mapping(target = "assignedGroupId", ignore = true)
    @Mapping(target = "closedAt", ignore = true)
    Ticket toEntity(CreateTicketRequest request);

    /**
     * Applies mutable fields from an update request onto an existing Ticket.
     * All service-managed fields are left untouched.
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "ticketNo", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "assignedUserId", ignore = true)
    @Mapping(target = "assignedGroupId", ignore = true)
    @Mapping(target = "customerId", ignore = true)
    @Mapping(target = "closedAt", ignore = true)
    void updateEntity(UpdateTicketRequest request, @MappingTarget Ticket ticket);
}
