package com.caseflow.ticket.api.mapper;

import com.caseflow.ticket.api.dto.AttachmentMetadataResponse;
import com.caseflow.ticket.api.dto.CreateTicketRequest;
import com.caseflow.ticket.api.dto.HistorySummaryResponse;
import com.caseflow.ticket.api.dto.TicketDetailResponse;
import com.caseflow.ticket.api.dto.TicketResponse;
import com.caseflow.ticket.api.dto.TicketSummaryResponse;
import com.caseflow.ticket.api.dto.UpdateTicketRequest;
import com.caseflow.ticket.domain.Ticket;
import org.mapstruct.BeanMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;
import org.mapstruct.NullValuePropertyMappingStrategy;
import org.mapstruct.ReportingPolicy;

import java.util.List;

@Mapper(
        componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.ERROR,
        unmappedSourcePolicy = ReportingPolicy.IGNORE
)
public interface TicketMapper {

    // ── Entity → Response ─────────────────────────────────────────────────────

    TicketResponse toResponse(Ticket ticket);

    TicketSummaryResponse toSummaryResponse(Ticket ticket);

    /**
     * Maps core Ticket fields only. Attachments and history come from separate
     * service calls and must be provided via the overloaded assembly method below.
     */
    @Mapping(target = "attachments", ignore = true)
    @Mapping(target = "history", ignore = true)
    TicketDetailResponse toDetailResponse(Ticket ticket);

    /**
     * Full TicketDetailResponse assembly. Attachments and history are resolved
     * by the caller (controller/facade) before invoking this method.
     */
    default TicketDetailResponse toDetailResponse(Ticket ticket,
                                                   List<AttachmentMetadataResponse> attachments,
                                                   List<HistorySummaryResponse> history) {
        TicketDetailResponse base = toDetailResponse(ticket);
        return new TicketDetailResponse(
                base.id(),
                base.ticketNo(),
                base.subject(),
                base.description(),
                base.status(),
                base.priority(),
                base.customerId(),
                base.assignedUserId(),
                base.assignedGroupId(),
                base.createdAt(),
                base.updatedAt(),
                base.closedAt(),
                attachments,
                history
        );
    }

    // ── Request → Entity ──────────────────────────────────────────────────────

    /**
     * Maps creatable fields from request. ticketNo is generated by service.
     * status, assignedUserId, assignedGroupId, and closedAt are service-managed.
     * createdBy is a service-layer concern (used for history), not an entity field.
     */
    @Mapping(target = "ticketNo", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "assignedUserId", ignore = true)
    @Mapping(target = "assignedGroupId", ignore = true)
    @Mapping(target = "closedAt", ignore = true)
    Ticket toEntity(CreateTicketRequest request);

    /**
     * Applies mutable fields from an update request onto an existing Ticket.
     * All service-managed fields are left untouched.
     */
    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "ticketNo", ignore = true)
    @Mapping(target = "status", ignore = true)
    @Mapping(target = "assignedUserId", ignore = true)
    @Mapping(target = "assignedGroupId", ignore = true)
    @Mapping(target = "customerId", ignore = true)
    @Mapping(target = "closedAt", ignore = true)
    void updateEntity(UpdateTicketRequest request, @MappingTarget Ticket ticket);
}
