apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caseflow-ingress
  namespace: caseflow
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
spec:
  ingressClassName: nginx
  rules:
    - host: caseflow.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: caseflow-svc
                port:
                  number: 8080
