apiVersion: v1
kind: Service
metadata:
  name: caseflow-svc
  namespace: caseflow
  labels:
    app: caseflow
spec:
  selector:
    app: caseflow
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
