package com.caseflow.notification.domain;

/**
 * Types of user notifications generated by ticket lifecycle events.
 */
public enum NotificationType {
    /** Ticket created and assigned to a group the user belongs to. */
    TICKET_CREATED_FOR_GROUP,
    /** Ticket first-assigned to this specific user. */
    TICKET_ASSIGNED_TO_USER,
    /** Ticket reassigned to this specific user from someone else. */
    TICKET_REASSIGNED_TO_USER
}
